### ISSUE TITLE
Random crashes for no apparent reason, can't find incompatible mod.

### ISSUE THREAD

**Issue by ghost** [Yesssssman/epicfightmod#1067]
[crash-2022-06-25_16.43.55-client.txt](https://github.com/Yesssssman/epicfightmod/files/8985887/crash-2022-06-25_16.43.55-client.txt)
Epic Fight version 16.5.13

**Comment by demolition86** [comment]
Thanks! Do you ever think it will be compatible in a future update?

**Comment by Yesssssman** [comment]
Well.. I don't think it's a problem with a specific mod. it is pretty a complicated issue and needs much effort to be figured out. I'm not sure it would even be solved in the future but I won't close this issue tab and I'm going to work on the hard issues at once.

**Comment by KarinMiku** [comment]
any news about this issue? still happening with latest oculus + rubidium (oculus-1.2.5a / rubidium-1.16.5-0.2.8) sadly U n U

**Comment by Kasualix** [comment]
Would like to provide more crash info: https://pastebin.ubuntu.com/p/h7nzJhMGkY/
Mixin Trace dumped by [my mod](https://github.com/MCTeamPotato/Opotato/tree/main/src/main/java/com/teampotato/opotato/mixin/mixintrace)

**Comment by Kasualix** [comment]
I add a rough workaround to fix this crash in [my mod](https://www.curseforge.com/minecraft/mc-mods/opotato).

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
