### ISSUE TITLE
[Bug|Crash]: Performing Steel Whirlwind attack crashes the game for other players who witness it.

### ISSUE THREAD

**Issue by MakkuSaiko** [Yesssssman/epicfightmod#1672]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

When my brother used a Steel Whirlwind attack, my game crashed. The same happened with other players on our server when they were in close proximity to my brother.
Please see logs below:

[Exception Stack Trace.txt](https://github.com/user-attachments/files/15943897/Exception.Stack.Trace.txt)
[Full Log.log](https://github.com/user-attachments/files/15943898/Full.Log.log)

Unfortunately I did not save the log for server side, but I did check the console when people crashed and It did not show anything that seemed related to the crash (Actually i think it just showed "User Disconnected"). I will attempt to reproduce the error sometime and send the server side log if you need it.

As for a possible fix for the issue: I did change the following in the animations class when tinkering with the code myself:
![image](https://github.com/Yesssssman/epicfightmod/assets/78232340/d493ec97-4447-4994-93c3-e30362976bb2)
It did fortunately stop the crashing when the skill is used as I tested it with my brother.

**Comment by Yesssssman** [comment]
This is the result of when I tested Steel Whirlwind on my desktop.

https://github.com/Yesssssman/epicfightmod/assets/79469058/2a201fdd-86ce-4b04-a88f-0cc0bc6b34cc

Used Epic Fight 19.5.24

If this bug is related to an old random server crash issue (which we called as Thanos bug), Sadly there's nothing I can do for now.

**Comment by Yesssssman** [comment]
I found the reason. If you assign Steel Whirlwind animation using datapack to weapons that don't have the skill as their innate, the game crashes.

**Comment by Yesssssman** [comment]
I'll check if the player has Steel Whirlwind. Then it won't create NullPointerException anymore. Thank you for reporting!

**Comment by Rxnzo** [comment]
Do you happen to have shoulder surfing on your server?

**Comment by Yesssssman** [comment]
Fixed in 19.5.26. Enjoy it!

**Comment by Chaneriel** [comment]
Not fixed for me. Im playing DawnCraft 2.10.13 using Epic Fight 18.5.26. We have Shoulder surfer but out of everyone on my server im the only one who crashes. 

EDIT: Removing shoulder surfer did not fix it. We all fresh installed and its only me with the issue

[crash-2025-01-01_20.54.42-client.txt](https://github.com/user-attachments/files/18287263/crash-2025-01-01_20.54.42-client.txt)

**Comment by guivnf** [comment]
> Not fixed for me. Im playing DawnCraft 2.10.13 using Epic Fight 18.5.26. 

Then it's dawncraft's issue. The issue has been solved on newer versions which they can move to.

**Comment by Chaneriel** [comment]
The modpack is using a version after the one that you said fixes the crash. The discord is completely useless as is the modded minecraft discord. I also dont understand why its only me

**Comment by guivnf** [comment]
> The modpack is using a version after the one that you said fixes the crash. The discord is completely useless as is the modded minecraft discord. I also dont understand why its only me

Most likely this issue was only fixed on 1.19.2+, so report that to them, as the issue itself does not remain on newer supported versions. 1.18.2 is discontinued
