### ISSUE TITLE
[Bug]: The longsword's Weapon Innate Skill cannot be toggled off.

### ISSUE THREAD

**Issue by latiaotiao** [Yesssssman/epicfightmod#2208]
### Please check if a similar issue has already been reported.

- [x] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [x] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [x] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [x] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

The longsword's Weapon Innate Skill cannot be toggled off.

### Steps to Reproduce

The 'Liechtenauer' weapon innate skill (for longswords) does not deactivate when the skill key is pressed a second time.

**Comment by EchoEllet** [comment]
Thank you for the report. That's a known regression (#2196).
We have fixed this issue in `20.13.6-1.20.1` and `21.13.5-1.21.1`.
Please consider updating Epic Fight to the latest version and let me know if that fixed the issue for you.

**Comment by latiaotiao** [comment]
I am actually using version 20.13.6-1.20.1, but the issue still persists.

**Comment by EchoEllet** [comment]
Was this an issue in older versions?

> The 'Liechtenauer' weapon innate skill (for longswords) does not deactivate when the skill key is pressed a second time.

I have tested this now, and it seems to work; I could not reproduce the bug.

FYI: There is a cooldown on how often the player can activate this. Maybe this is related?

<img width="175" height="180" alt="Image" src="https://github.com/user-attachments/assets/12153616-5e72-4512-9976-148a1816ddcd" />

**Comment by latiaotiao** [comment]
The countdown is the duration of the defensive stance.In the older version (20.9.7), it was possible to manually cancel​ the stance by pressing the skill key again. This issue has been present for a considerable time. Initially, I thought it was an intentional mechanic change, but after reviewing the code,  it appears the logic for manual cancellation still exists—it just isn’t being triggered correctly.
